on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: checkout
      uses: actions/checkout
    - name: Hello Action step
      id: hello
      uses: ./
      with:
        whot-to-greet: "Marcelo"
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
